import unittest
from bs4 import BeautifulSoup
from acl.conference import Conference


class TestConference(unittest.TestCase):

    def test_set_anthology(self):
        element = BeautifulSoup(PAGE.strip(), "html.parser")
        c = Conference("http://dummy")
        c.set_anthology(element)

        self.assertEqual(len(c.anthologies), 4)

        for i, k in enumerate(c.anthologies):
            a = c.anthologies[k]
            if i == 0:
                self.assertEqual(k, "J00-1")
                self.assertEqual(a.name, "Computational Linguistics, Volume 26, Number 1, March 2000")
                self.assertEqual(a.count, 7)
            elif i == 1:
                self.assertEqual(k, "J00-2")
                self.assertEqual(a.name, "Computational Linguistics, Volume 26, Number 2, June 2000")
                self.assertEqual(a.count, 18)
            elif i == 2:
                self.assertEqual(k, "J00-3")
                self.assertEqual(a.name, "Computational Linguistics, Volume 26, Number 3, September 2000")
                self.assertEqual(a.count, 12)
            elif i == 3:
                self.assertEqual(k, "J00-4")
                self.assertEqual(a.name, "Computational Linguistics, Volume 26, Number 4, December 2000")
                self.assertEqual(a.count, 14)

    def test_retrieve_from_element(self):
        element = BeautifulSoup(PAGE.strip(), "html.parser")
        c = Conference("http://dummy")
        result = c.retrieve_from_element(element, "J00-1")
        papers = result.papers
        self.assertEqual(len(papers), 1)
        for k in result.papers:
            self.assertEqual(k, "J00-1")
            self.assertEqual(len(papers[k]), 7)
            self.assertEqual(papers[k][0].title, "Introduction to the Special issue on finite state methods in NLP")
            self.assertEqual(papers[k][-1].title, "Advertisements")

    def xtest_retrieve_from_url(self):
        c = Conference.ACL(2018)
        result = c.retrieve("P18-5")
        self.assertEqual(len(result.papers), 1)
        papers = result.papers
        for k in papers:
            self.assertEqual(k, "P18-5")
            self.assertEqual(len(papers[k]), 9)
            self.assertEqual(papers[k][0].title, "Proceedings of ACL 2018, Tutorial Abstracts")
            self.assertEqual(papers[k][-1].title, "Multi-lingual Entity Discovery and Linking")


# URL: https://www.aclweb.org/anthology/events/cl-2000/

PAGE = """
<html lang="en-us" class="gr__aclweb_org"><head><meta charset="utf-8"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><!--[if IEMobile]><meta http-equiv=cleartype content=on><![endif]--><title>Computational Linguistics Journal (2000) - ACL Anthology</title><meta name="generator" content="Hugo 0.54.0"><link href="/anthology/aclicon.ico" rel="shortcut icon" type="image/x-icon"><link rel="stylesheet" href="/anthology/css/main.min.ba3d6e9b0848f8f76897d75085eb7071962d72ee7a4a823e9c2a5e729158e8ad.css" media="screen"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"></head><body data-gr-c-s-loaded="true"><nav class="navbar navbar-expand navbar-light bg-gradient-light shadow-sm py-0 mb-3 mb-md-4 mb-xl-5"><div id="navbar-container" class="container"><a class="navbar-brand" href="/anthology/"><img src="/anthology/images/acl-logo.svg" width="56" alt="ACL Logo">
<span class="d-none d-md-inline pl-md-2">ACL Anthology</span></a><form class="form-inline flex-nowrap ml-auto my-1 my-sm-2" action="/anthology/search/?" method="get"><input id="acl-search-box" class="form-control mr-1 mr-sm-2" name="q" type="search" placeholder="Search..." aria-label="Search">
<button class="btn btn-outline-primary" type="submit"><i class="fas fa-search"></i></button></form></div></nav><div class="container"><aside class="alert alert-warning text-center py-1 mt-n3 mt-md-n4 mt-xl-n5" role="alert">You're viewing the latest version of the ACL Anthology.
<a class="btn btn-warning mx-2" href="https://github.com/acl-org/acl-anthology/issues/170">Give feedback</a></aside></div><div id="main-container" class="container"><section id="main"><h2 id="title">Computational Linguistics Journal (2000)</h2><hr><div class="card bg-light mb-2 mb-lg-4"><div class="card-body"><h4 class="card-title">Contents</h4><ul class="list-pl-responsive"><li><span class="text-muted align-middle">[J00-1]:&nbsp;</span>
<a class="align-middle" href="#j00-1">Computational Linguistics, Volume 26, Number 1, March 2000</a>
<span class="badge badge-info align-middle ml-1">7&nbsp;papers</span></li><li><span class="text-muted align-middle">[J00-2]:&nbsp;</span>
<a class="align-middle" href="#j00-2">Computational Linguistics, Volume 26, Number 2, June 2000</a>
<span class="badge badge-info align-middle ml-1">18&nbsp;papers</span></li><li><span class="text-muted align-middle">[J00-3]:&nbsp;</span>
<a class="align-middle" href="#j00-3">Computational Linguistics, Volume 26, Number 3, September 2000</a>
<span class="badge badge-info align-middle ml-1">12&nbsp;papers</span></li><li><span class="text-muted align-middle">[J00-4]:&nbsp;</span>
<a class="align-middle" href="#j00-4">Computational Linguistics, Volume 26, Number 4, December 2000</a>
<span class="badge badge-info align-middle ml-1">14&nbsp;papers</span></li></ul></div></div><div id="j00-1"><small><a href="#" class="text-muted"><i class="fas fa-arrow-up"></i>up</a></small><h4 class="pb-2"><span class="mr-2"><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Computational+Linguistics%2C+Volume+26%2C+Number+1%2C+March+2000" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><a class="align-middle" href="/anthology/volumes/computational-linguistics-volume-26-number-1-march-2000/">Computational Linguistics, Volume 26, Number 1, March 2000</a></h4><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1001" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1001.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Introduction+to+the+Special+issue+on+finite+state+methods+in+NLP" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1001/">Introduction to the Special issue on finite state methods in <span class="acl-fixed-case">NLP</span></a></strong><br><span class="text-muted">[J00-1001]:</span>
<a href="/anthology/people/l/lauri-karttunen/">Lauri Karttunen</a>
|
<a href="/anthology/people/k/kemal-oflazer/">Kemal Oflazer</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1002" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1002.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Incremental+construction+of+minimal+acyclic+finite+state+automata" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1002/">Incremental construction of minimal acyclic finite state automata</a></strong><br><span class="text-muted">[J00-1002]:</span>
<a href="/anthology/people/j/jan-daciuk/">Jan Daciuk</a>
|
<a href="/anthology/people/s/stoyan-mihov/">Stoyan Mihov</a>
|
<a href="/anthology/people/b/bruce-w-watson/">Bruce W. Watson</a>
|
<a href="/anthology/people/r/richard-e-watson/">Richard E. Watson</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1003" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1003.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Practical+Experiments+with+Regular+Approximation+of+Context-Free+Languages" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1003/">Practical Experiments with Regular Approximation of Context-Free Languages</a></strong><br><span class="text-muted">[J00-1003]:</span>
<a href="/anthology/people/m/mark-jan-nederhof/">Mark-Jan Nederhof</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1004" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1004.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Learning+dependency+translation+models+as+collections+of+finite+state+head+transducers" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1004/">Learning dependency translation models as collections of finite state head transducers</a></strong><br><span class="text-muted">[J00-1004]:</span>
<a href="/anthology/people/h/hiyan-alshawi/">Hiyan Alsawi</a>
|
<a href="/anthology/people/s/srinivas-bangalore/">Srinivas Bangalore</a>
|
<a href="/anthology/people/s/shona-douglas/">Shona Douglas</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1005" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1005.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Treatment+of+epsilon+moves+in+subset+construction" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1005/">Treatment of epsilon moves in subset construction</a></strong><br><span class="text-muted">[J00-1005]:</span>
<a href="/anthology/people/g/gertjan-van-noord/">Gertjan van Noord</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1006" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1006.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Multitiered+nonlinear+morphology+using+multitape+finite+automata%3A+a+case+study+on+Syriac+and+Arabic" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1006/">Multitiered nonlinear morphology using multitape finite automata: a case study on <span class="acl-fixed-case">Syriac</span> and <span class="acl-fixed-case">Arabic</span></a></strong><br><span class="text-muted">[J00-1006]:</span>
<a href="/anthology/people/g/george-anton-kiraz/">George Anton Kiraz</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-1007" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-1007.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Advertisements" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-1007/">Advertisements</a></strong><br><span class="text-muted">[J00-1007]:</span></p></div><hr><div id="j00-2"><small><a href="#" class="text-muted"><i class="fas fa-arrow-up"></i>up</a></small><h4 class="pb-2"><span class="mr-2"><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Computational+Linguistics%2C+Volume+26%2C+Number+2%2C+June+2000" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><a class="align-middle" href="/anthology/volumes/computational-linguistics-volume-26-number-2-june-2000/">Computational Linguistics, Volume 26, Number 2, June 2000</a></h4><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2001" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2001.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Integrating+Text+planning+and+linguistic+choice+without+abandoning+modularity%3A+the+IGEN+generator" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2001/">Integrating Text planning and linguistic choice without abandoning modularity: the <span class="acl-fixed-case">IGEN</span> generator</a></strong><br><span class="text-muted">[J00-2001]:</span>
<a href="/anthology/people/r/robert-rubinoff/">Robert Rubinoff</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2002" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2002.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=A+model+for+multimodal+reference+resolution" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2002/">A model for multimodal reference resolution</a></strong><br><span class="text-muted">[J00-2002]:</span>
<a href="/anthology/people/l/luis-a-pineda/">Luis Pineda</a>
|
<a href="/anthology/people/e/e-gabriela-garza/">Gabriela Garza</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2003" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2003.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=A+multistrategy+approach+to+improving+pronunciation+by+analogy" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2003/">A multistrategy approach to improving pronunciation by analogy</a></strong><br><span class="text-muted">[J00-2003]:</span>
<a href="/anthology/people/y/yannick-marchand/">Yannick Marchand</a>
|
<a href="/anthology/people/r/robert-i-damper/">Robert I. Damper</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2004" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2004.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Models+of+translation+equivalence+among+words" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2004/">Models of translation equivalence among words</a></strong><br><span class="text-muted">[J00-2004]:</span>
<a href="/anthology/people/i/i-dan-melamed/">I. Dan Melamed</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2005" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2005.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Pipelines+and+size+constraints" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2005/">Pipelines and size constraints</a></strong><br><span class="text-muted">[J00-2005]:</span>
<a href="/anthology/people/e/ehud-reiter/">Ehud Reiter</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2006" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2006.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+A+Grammar+Writer%E2%80%99s+Cookbook" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2006/">Book Reviews: A Grammar Writer’s Cookbook</a></strong><br><span class="text-muted">[J00-2006]:</span>
<a href="/anthology/people/m/michael-maxwell/">Michael Maxwell</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2007" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2007.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Local+Constraints+vs.+Economy" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2007/">Book Reviews: Local Constraints vs. Economy</a></strong><br><span class="text-muted">[J00-2007]:</span>
<a href="/anthology/people/a/annie-zaenen/">Annie Zaenen</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2008" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2008.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Predicative+Forms+in+Natural+Language+and+in+Lexical+Knowledge+Bases" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2008/">Book Reviews: Predicative Forms in Natural Language and in Lexical Knowledge Bases</a></strong><br><span class="text-muted">[J00-2008]:</span>
<a href="/anthology/people/m/manfred-stede/">Manfred Stede</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2009" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2009.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Lexical+Semantics+and+Knowledge+Representation+in+Multilingual+Text+Generation" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2009/">Book Reviews: Lexical Semantics and Knowledge Representation in Multilingual Text Generation</a></strong><br><span class="text-muted">[J00-2009]:</span>
<a href="/anthology/people/b/barbara-di-eugenio/">Barbara Di Eugenio</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2010" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2010.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+The+Mathematics+of+Syntactic+Structure%3A+Trees+and+their+Logics" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2010/">Book Reviews: The Mathematics of Syntactic Structure: Trees and their Logics</a></strong><br><span class="text-muted">[J00-2010]:</span>
<a href="/anthology/people/g/gerald-penn/">Gerald Penn</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2011" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2011.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Foundations+of+Statistical+Natural+Language+Processing" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2011/">Book Reviews: Foundations of Statistical Natural Language Processing</a></strong><br><span class="text-muted">[J00-2011]:</span>
<a href="/anthology/people/l/lillian-lee/">Lillian Lee</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2012" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2012.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Advances+in+Automatic+Text+Summarization" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2012/">Book Reviews: Advances in Automatic Text Summarization</a></strong><br><span class="text-muted">[J00-2012]:</span>
<a href="/anthology/people/m/mark-sanderson/">Mark Sanderson</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2013" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2013.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Extended+Finite+State+Models+of+Language" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2013/">Book Reviews: Extended Finite State Models of Language</a></strong><br><span class="text-muted">[J00-2013]:</span>
<a href="/anthology/people/e/ed-kaiser/">Ed Kaiser</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2014" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2014.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Optimality+Theory" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2014/">Book Reviews: Optimality Theory</a></strong><br><span class="text-muted">[J00-2014]:</span>
<a href="/anthology/people/j/jason-eisner/">Jason Eisner</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2015" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2015.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Systemic+Functional+Grammar+in+Natural+Language+Generation%3A+Linguistic+Description+and+Computational+Representation" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2015/">Book Reviews: Systemic Functional Grammar in Natural Language Generation: Linguistic Description and Computational Representation</a></strong><br><span class="text-muted">[J00-2015]:</span>
<a href="/anthology/people/g/graham-wilcock/">Graham Wilcock</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2016" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2016.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Briefly+Noted" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2016/">Briefly Noted</a></strong><br><span class="text-muted">[J00-2016]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2017" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2017.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Publications+Received" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2017/">Publications Received</a></strong><br><span class="text-muted">[J00-2017]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-2018" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-2018.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Advertisements" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-2018/">Advertisements</a></strong><br><span class="text-muted">[J00-2018]:</span></p></div><hr><div id="j00-3"><small><a href="#" class="text-muted"><i class="fas fa-arrow-up"></i>up</a></small><h4 class="pb-2"><span class="mr-2"><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Computational+Linguistics%2C+Volume+26%2C+Number+3%2C+September+2000" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><a class="align-middle" href="/anthology/volumes/computational-linguistics-volume-26-number-3-september-2000/">Computational Linguistics, Volume 26, Number 3, September 2000</a></h4><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3001" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3001.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Extracting+the+lowest-frequency+words%3A+pitfalls+and+possibilities" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3001/">Extracting the lowest-frequency words: pitfalls and possibilities</a></strong><br><span class="text-muted">[J00-3001]:</span>
<a href="/anthology/people/m/marc-weeber/">Marc Weeber</a>
|
<a href="/anthology/people/r/rein-vos/">Rein Vos</a>
|
<a href="/anthology/people/h/harald-baayen/">R. Harald Baayen</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3002" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3002.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Incremental+processing+and+acceptability" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3002/">Incremental processing and acceptability</a></strong><br><span class="text-muted">[J00-3002]:</span>
<a href="/anthology/people/g/glyn-morrill/">Glyn Morrill</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3003" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3003.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Dialogue+act+modeling+for+automatic+tagging+and+recognition+of+conversational+speech" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3003/">Dialogue act modeling for automatic tagging and recognition of conversational speech</a></strong><br><span class="text-muted">[J00-3003]:</span>
<a href="/anthology/people/a/andreas-stolcke/">Andreas Stolcke</a>
|
<a href="/anthology/people/k/klaus-ries/">Klaus Ries</a>
|
<a href="/anthology/people/n/noah-coccaro/">Noah Coccaro</a>
|
<a href="/anthology/people/e/elizabeth-shriberg/">Elizabeth Shriberg</a>
|
<a href="/anthology/people/r/rebecca-bates/">Rebecca Bates</a>
|
<a href="/anthology/people/d/dan-jurafsky/">Daniel Jurafsky</a>
|
<a href="/anthology/people/p/paul-taylor/">Paul Taylor</a>
|
<a href="/anthology/people/r/rachel-martin/">Rachel Martin</a>
|
<a href="/anthology/people/c/carol-van-ess-dykema/">Carol Van Ess-Dykema</a>
|
<a href="/anthology/people/m/marie-meteer/">Marie Meteer</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3004" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3004.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=A+compression+based+algorithm+for+Chinese+word+segmentation" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3004/">A compression based algorithm for <span class="acl-fixed-case">Chinese</span> word segmentation</a></strong><br><span class="text-muted">[J00-3004]:</span>
<a href="/anthology/people/w/william-j-teahan/">W. J. Teahan</a>
|
<a href="/anthology/people/y/yingying-wen/">Yingying Wen</a>
|
<a href="/anthology/people/r/rodger-mcnab/">Rodger McNab</a>
|
<a href="/anthology/people/i/ian-h-witten/">Ian H. Witten</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3005" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3005.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=The+rhetorical+parsing+of+unrestricted+texts%3A+a+surface-based+approach" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3005/">The rhetorical parsing of unrestricted texts: a surface-based approach</a></strong><br><span class="text-muted">[J00-3005]:</span>
<a href="/anthology/people/d/daniel-marcu/">Daniel Marcu</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3006" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3006.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Foundations+of+Computational+Linguistics%3A+Man-Machine+Communication+in+Natural+Language" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3006/">Book Reviews: Foundations of Computational Linguistics: Man-Machine Communication in Natural Language</a></strong><br><span class="text-muted">[J00-3006]:</span>
<a href="/anthology/people/a/alexander-gelbukh/">Alexander F. Gelbukh</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3007" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3007.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Syntactic+Wordclass+Tagging" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3007/">Book Reviews: Syntactic Wordclass Tagging</a></strong><br><span class="text-muted">[J00-3007]:</span>
<a href="/anthology/people/a/adwait-ratnaparkhi/">Adwait Ratnaparkhi</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3008" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3008.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Natural+Language+Information+Retrieval" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3008/">Book Reviews: Natural Language Information Retrieval</a></strong><br><span class="text-muted">[J00-3008]:</span>
<a href="/anthology/people/s/simon-corston-oliver/">Simon Corston-Oliver</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3009" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3009.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+The+MIT+Encyclopedia+of+the+Cognitive+Sciences" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3009/">Book Reviews: The MIT Encyclopedia of the Cognitive Sciences</a></strong><br><span class="text-muted">[J00-3009]:</span>
<a href="/anthology/people/j/john-nerbonne/">John Nerbonne</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3010" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3010.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Publications+Received" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3010/">Publications Received</a></strong><br><span class="text-muted">[J00-3010]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3011" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3011.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Erratum" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3011/">Erratum</a></strong><br><span class="text-muted">[J00-3011]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-3012" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-3012.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Advertisements" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-3012/">Advertisements</a></strong><br><span class="text-muted">[J00-3012]:</span></p></div><hr><div id="j00-4"><small><a href="#" class="text-muted"><i class="fas fa-arrow-up"></i>up</a></small><h4 class="pb-2"><span class="mr-2"><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Computational+Linguistics%2C+Volume+26%2C+Number+4%2C+December+2000" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><a class="align-middle" href="/anthology/volumes/computational-linguistics-volume-26-number-4-december-2000/">Computational Linguistics, Volume 26, Number 4, December 2000</a></h4><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4001" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4001.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Automatic+Text+Categorization+In+Terms+Of+Genre+and+Author" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4001/">Automatic Text Categorization In Terms Of Genre and Author</a></strong><br><span class="text-muted">[J00-4001]:</span>
<a href="/anthology/people/e/efstathios-stamatatos/">Efstathios Stamatatos</a>
|
<a href="/anthology/people/n/nikos-fakotakis/">Nikos Fakotakis</a>
|
<a href="/anthology/people/g/george-kokkinakis/">George Kokkinakis</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4002" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4002.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Bidirectional+Contextual+Resolution" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4002/">Bidirectional Contextual Resolution</a></strong><br><span class="text-muted">[J00-4002]:</span>
<a href="/anthology/people/s/stephen-pulman/">Stephen G. Pulman</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4003" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4003.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=An+Empirically-based+System+for+Processing+Definite+Descriptions" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4003/">An Empirically-based System for Processing Definite Descriptions</a></strong><br><span class="text-muted">[J00-4003]:</span>
<a href="/anthology/people/r/renata-vieira/">Renata Vieira</a>
|
<a href="/anthology/people/m/massimo-poesio/">Massimo Poesio</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4004" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4004.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Learning+Methods+to+Combine+Linguistic+Indicators%3AImproving+Aspectual+Classification+and+Revealing+Linguistic+Insights" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4004/">Learning Methods to Combine Linguistic Indicators:Improving Aspectual Classification and Revealing Linguistic Insights</a></strong><br><span class="text-muted">[J00-4004]:</span>
<a href="/anthology/people/e/eric-v-siegel/">Eric V. Siegel</a>
|
<a href="/anthology/people/k/kathleen-mckeown1/">Kathleen R. McKeown</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4005" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4005.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=On+Coreferring%3A+Coreference+in+MUC+and+Related+Annotation+Schemes" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4005/">On Coreferring: Coreference in <span class="acl-fixed-case">MUC</span> and Related Annotation Schemes</a></strong><br><span class="text-muted">[J00-4005]:</span>
<a href="/anthology/people/k/kees-van-deemter/">Kees van Deemter</a>
|
<a href="/anthology/people/r/rodger-kibble/">Rodger Kibble</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4006" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4006.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Speech+and+Language+Processing%3A+An+Introduction+to+Natural+Language+Processing%2C+Computational+Linguistics%2C+and+Speech+Recognition" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4006/">Book Reviews: Speech and Language Processing: An Introduction to Natural Language Processing, Computational Linguistics, and Speech Recognition</a></strong><br><span class="text-muted">[J00-4006]:</span>
<a href="/anthology/people/v/virginia-teller/">Virginia Teller</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4007" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4007.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Artificial+Intelligence+and+Literary+Creativity%3A+Inside+the+Mind+of+BRUTUS%2C+a+Storytelling+Machine" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4007/">Book Reviews: Artificial Intelligence and Literary Creativity: Inside the Mind of BRUTUS, a Storytelling Machine</a></strong><br><span class="text-muted">[J00-4007]:</span>
<a href="/anthology/people/r/ronald-de-sousa/">Ronald de Sousa</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4008" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4008.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Architectures+and+Mechanisms+for+Language+Processing" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4008/">Book Reviews: Architectures and Mechanisms for Language Processing</a></strong><br><span class="text-muted">[J00-4008]:</span>
<a href="/anthology/people/a/amy-weinberg/">Amy Weinberg</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4009" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4009.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Book+Reviews%3A+Breadth+and+Depth+of+Semantic+Lexicons" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4009/">Book Reviews: Breadth and Depth of Semantic Lexicons</a></strong><br><span class="text-muted">[J00-4009]:</span>
<a href="/anthology/people/j/john-s-white/">John S. White</a></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4010" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4010.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Briefly+Noted" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4010/">Briefly Noted</a></strong><br><span class="text-muted">[J00-4010]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4011" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4011.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Publications+Received" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4011/">Publications Received</a></strong><br><span class="text-muted">[J00-4011]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4012" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4012.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Author+Index%3A+Volume+26" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4012/">Author Index: Volume 26</a></strong><br><span class="text-muted">[J00-4012]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4013" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4013.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Title+Index%3A+Volume+2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4013/">Title Index: Volume 2</a></strong><br><span class="text-muted">[J00-4013]:</span></p><p><span class="mr-2"><a class="badge badge-primary align-middle mr-1" href="https://www.aclweb.org/anthology/J00-4014" data-toggle="tooltip" data-placement="top" title="" data-original-title="Open PDF">pdf
</a><a class="badge badge-secondary align-middle mr-1" href="/anthology/papers/J/J00/J00-4014.bib" data-toggle="tooltip" data-placement="top" title="" data-original-title="Export to BibTeX">bib
</a><a class="badge badge-secondary align-middle mr-1" href="https://www.google.com/search?q=Advertisements" data-toggle="tooltip" data-placement="top" title="" data-original-title="Search on Google"><i class="fas fa-search"></i></a></span><strong><a class="align-middle" href="/anthology/papers/J/J00/J00-4014/">Advertisements</a></strong><br><span class="text-muted">[J00-4014]:</span></p></div><hr></section></div><footer class="bg-gradient-light py-2 py-xl-3 mt-3 mt-md-4 mt-xl-5"><div class="container"><nav role="navigation" class="nav w-100 justify-content-center"><a class="nav-link" href="/anthology/info/credits/">Credits</a>
<a class="nav-link" href="/anthology/faq/">FAQ</a>
<a class="nav-link" href="/anthology/info/contrib/">For Contributors</a>
<a class="nav-link" href="http://bit.ly/aclAnthologyQ">Ingestion Queue</a>
<a class="nav-link" href="https://github.com/acl-org/acl-anthology/issues/">Issues</a>
<a class="nav-link" href="/anthology/info/corrections/">Request Corrections</a>
<a class="nav-link" href="/anthology/info/volunteer/">Volunteer!</a></nav><hr class="mt-2"></div><div class="container"><p class="text-muted small px-1"><span class="float-right mt-2"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png"></a></span>
ACL materials are Copyright ©&nbsp;1963–2019 ACL; other materials are copyrighted by their respective copyright holders. Materials prior to 2016 here are licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 International License</a>. Permission is granted to make copies for the purposes of teaching and research. Materials published in or after 2016 are licensed on a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.</p><p class="text-muted small px-1"><a href="http://mjpost.github.io/">Matt Post</a> (Editor, 2019–) |
<a href="http://www.comp.nus.edu.sg/~kanmy/">Min-Yen Kan</a> (Editor, 2008–2018) |
<a href="http://stevenbird.net/">Steven Bird</a> (Editor, 2001–2007)</p></div></footer><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script><script>$(function(){$('[data-toggle="tooltip"]').tooltip()})</script></body><div><div class="gr_-editor gr-iframe-first-load" style="display: none;"><div class="gr_-editor_back"></div><iframe class="gr_-ifr gr-_dialog-content"></iframe></div></div><grammarly-card><div></div></grammarly-card><span class="gr__tooltip"><span class="gr__tooltip-content"></span><i class="gr__tooltip-logo"></i><span class="gr__triangle"></span></span></html>
"""
